name: Hello-world

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do something
        run: echo "Hello from GitHub Actions!"
